Signing commit 29-11-2020

diff --git a/docker/php/Dockerfile b/docker/php/Dockerfile
--- a/docker/php/Dockerfile
+++ b/docker/php/Dockerfile
@@ -63,26 +63,126 @@ ENV PATH "${COMPOSER_HOME}/vendor/bin:$PATH"
 #######################################################################
 
 # persistent dependencies
-RUN --mount=type=cache,target=/var/cache/apk \
-  ln -s /var/cache/apk /etc/apk/cache && apk update && apk add \
-  build-base \
-  curl \
-  bash \
-  git \
-  vim \
-  unzip
+RUN --mount=type=cache,target=/var/cache/apk ln -sf /var/cache/apk /etc/apk/cache; \
+  set -euo pipefail \
+  && apk add --update \
+    build-base \
+    bash \
+    unzip \
+    curl \
+    ca-certificates \
+    openssl \
+    tzdata
+
+# && rm -rf /var/cache/apk/*
+
+#######################################################################
+# Setting the timezone
+# https://wiki.alpinelinux.org/wiki/Setting_the_timezone
+#######################################################################
+
+ARG TZ="Europe/Moscow"
+ENV TZ $TZ
+RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
 
 #######################################################################
 # Install PHP extensions
 #######################################################################
 
-COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/
-RUN --mount=type=cache,target=/var/cache/apk \
-  install-php-extensions \
-  intl \
-  opcache \
-  apcu \
-  redis
+#COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/
+#RUN --mount=type=cache,target=/var/cache/apk \
+#  install-php-extensions \
+#  intl \
+#  opcache \
+#  apcu \
+#  redis
+
+RUN --mount=type=cache,target=/var/cache/apk ln -sf /var/cache/apk /etc/apk/cache \
+  && set -xe \
+  && apk add --virtual .build-deps $PHPIZE_DEPS \
+  && apk add \
+    postgresql-dev \
+  && docker-php-source extract \
+  && docker-php-ext-install \
+    pdo \
+    pdo_pgsql \
+    intl \
+    iconv \
+    ctype \
+    json \
+    pcre \
+    session \
+    simplexml \
+    tokenizer \
+    opcache \
+  # PECL extensions
+  && pecl install \
+    apcu-5.1.19 \
+    redis-6.0.9 \
+    xdebug-3.0.0 \
+  && docker-php-ext-enable \
+    opcache \
+    apcu \
+    redis \
+    xdebug \
+  # cleanup
+  && docker-php-source delete \
+  && apk del .build-deps \
+  && rm -rf /tmp/* /var/cache/apk/*
+
+
+# https://git.alpinelinux.org/aports/tree/community/php7/APKBUILD
+# https://pecl.php.net/package/apcu
+
+#RUN
+#  set -euo pipefail \
+#  && docker-php-source extract \
+#  && apk add --virtual .build-deps $PHPIZE_DEPS \
+#
+#  ## Install PHP extensions
+#  && docker-php-ext-install \
+#
+#  ## PECL extensions
+#  && pecl install \
+#    apcu \
+#    redis \
+#    xdebug \
+#  && docker-php-ext-enable \
+#    apcu \
+#    redis \
+#    xdebug \
+#  ## cleanup
+#  && docker-php-source delete \
+#  && apk del .build-deps
+
+
+#RUN \
+#  --mount=type=cache,target=/tmp/* \
+#  --mount=type=cache,target=/var/cache/* \
+#  set -eux; \
+#  ln -s /var/cache/apk /etc/apk/cache \
+#  && apk update \
+#  ## Install extensions and utilities
+#  && apk add $PHPIZE_DEPS \
+#    postgresql-dev \
+#  && docker-php-source extract \
+#  ## Install required PHP extensions
+#  && docker-php-ext-install \
+#    pdo \
+#    pdo_pgsql \
+#    opcache \
+#    intl \
+#  ## PECL extensions
+#  && pecl install \
+#    apcu \
+#    redis \
+#    xdebug \
+#  && docker-php-ext-enable \
+#    xdebug \
+#    opcache \
+#  ## cleanup
+#  && docker-php-source delete
+
 
 #######################################################################
 # Default configuration
